Avoid dependency on 2.10.2-SNAPSHOT
Using 2.10.1 instead

Strangely, 2.10.0 does not work!

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project jena-jsonld: Compilation failure: Compilation failure:
[ERROR] c:\Users\stain\workspace\jena-jsonld\src\main\java\jenajsonld\JsonLDReader.java:[40,28] error: cannot find symbol
[ERROR] symbol:   class NodeFactory
[ERROR] location: package com.hp.hpl.jena.graph
[ERROR] c:\Users\stain\workspace\jena-jsonld\src\main\java\jenajsonld\JenaJSONLD.java:[23,36] error: cannot find symbol
[ERROR] symbol:   class RDFWriterRIOT
[ERROR] location: package org.apache.jena.riot.adapters
[ERROR] c:\Users\stain\workspace\jena-jsonld\src\main\java\jenajsonld\JsonLDWriter.java:[29,27] error: cannot find symbol
[ERROR] symbol:   class RDFFormat
[ERROR] location: package org.apache.jena.riot
[ERROR] c:\Users\stain\workspace\jena-jsonld\src\main\java\jenajsonld\JsonLDWriter.java:[31,34] error: package org.apache.jena.riot.writer does not exist
[ERROR] c:\Users\stain\workspace\jena-jsonld\src\main\java\jenajsonld\JsonLDWriter.java:[41,27] error: cannot find symbol
[ERROR] symbol: class WriterDatasetRIOTBase
[ERROR] c:\Users\stain\workspace\jena-jsonld\src\main\java\jenajsonld\JsonLDWriter.java:[43,18] error: cannot find symbol

Seems like Jena/riot is not following
[Semantic Versioning](http://semver.org/) as a patch-version change
should not cause code to not compile.